language: node_js
node_js:
- '0.12'
script:
- npm run-script test-ci
- npm run-script build-sdk
git:
  depth: 1
deploy:
  - provider: releases
    api_key:
      secure: jUE2mYhPRhTQ87cDcSXIiI1ncoqTq1vNeKJBqb8wbpkYE6Fmp5S7/nBV+iXNwyoV9Ls3LvvEz6FLjecX7UI2eVrLtjLGZhro9HqCBKoWDX7H6usLR6WBFeycY+0xFTTMRTTE/0LfTpOrZrbs03wyt8WhlyvKHoSBpjN6UPBEDvs=
    skip_cleanup: true
    file:
      - "build/appstax-js.zip"
      - "build/appstax.js"
      - "build/appstax.min.js"
    on:
      tags: true
  - provider: npm
    email: support@appstax.com
    api_key:
      secure: dgkw4z3O14gf/HK3J5eKklCtkr6IkK56dahwq+bcCD/VEVcUrMqTyde+y2pdIwN6ZGBiHLkiaEo7kwaoKDhO9HeIgQYI8UgOjqnegPfKiQJOynMcRSFH37MeWsCvIP7wHX8vEZ0negYRzYbXg79tIqfql7l9WdtAQ7hNN72PRGA=
    on:
      tags: true
